### ISSUE TITLE
Cannot autowire settings automatically

### ISSUE THREAD

**Issue by pedrocasado** [jbtronics/settings-bundle#10] opened 2024-04-28 18:09 UTC
Any reason why autowire not working properly?

Cannot autowire argument $appSettings of "App\Controller\DefaultController::inject()": it references class "App\Settings\AppSettings" but no such service exists.

I know that adding this line in services.yml it works, but it should be done automatically, right?

`App\Settings\AppSettings: ~`

https://github.com/pedrocasado/test-settings

**Comment by jbtronics** [comment] 2024-04-28 20:55
This is now fixed. This was caused by the SettingsTrait which made the constructor private and therefore the class non-instantiable.

However, then symfony's class discoverer ignores the settings classes and dont register them as services (even if we dont need the constructor later, as we have a custom factory method). I have done my tests with settings classes without the `SettingsTrait` (as it is not really required), so I never noticed before.

As a fix I have just made the constructor public again, and let them throw an exception on runtime. There might be a better approach by implementing a custom discovery logic, but the fix should be reasonable for now.

**Closed by jbtronics** 2024-04-28 20:55 UTC
