### ISSUE TITLE
Nullable properties are not recognized in twig when loaded from proxied classes

### ISSUE THREAD

**Issue by pedrocasado** [jbtronics/settings-bundle#13] opened 2024-05-15 00:04 UTC
Nullables properties are not being recognized in twig when using `settings_instance` function.

This only occurs when we have any service (FooService) injected that uses any Settings class like:

```
class FooService
{
    public function __construct(private readonly AppSettings $appSettings)
    {
    }

    public function getFoo(): string
    {
        return $this->appSettings->myString;
    }
}
```

 ```
class DefaultController extends AbstractController
    {
        public function __construct(private readonly FooService $fooService)
        {
        }

        #[Route('/', name: 'home')]
        public function home(): Response
        {
            return $this->render('home.html.twig');
        }
    }

```
Eg:

home.html.twig

    {% set settings = settings_instance('app') %}
    {{ dump(settings.myString) }}

Throws:

    Neither the property "myString" nor one of the methods "myString()", "getmyString()"/"ismyString()"/"hasmyString()" or "__call()" exist and have public access in class "Jbtronics\SettingsBundle\Proxies\__JB__\App\Settings\AppSettings".
    
https://github.com/pedrocasado/test-settings replicates the issue.

**Comment by jbtronics** [comment] 2024-05-19 22:07
That was quite the tricky issue, that occured everytime, when a property were lazily initialized with null and you tried to access it via twig.
The error only occured with twig, while accessing the property from PHP directly (e.g. `$settings->myString`) directly worked fine. The difference seemed  to be caused by the fact that twig somehow calls isset() on the property, and the lazy proxy logic returns false for null properties.

This is ultimately caused by the LazyProxyTrait of symfony/var-exporter, which was initially chosen as it was easy to implement. I am not sure if this an implementation bug in the symfony component or a general (not documented) limitation of lazy proxy pattern.

There is a second lazy loading mechanism in symfony/var-exporter called `LazyGhostTrait` which works differently inside and which is also used by doctrine ORM internally. This seems to not have this problem and is probably in general the better choice for the purposes we use it in this bundle.

I changed the logic how proxies are generatedi internally to use the LazyGhostTrait and now this issue should be fixed with the latest commit.

**Closed by jbtronics** 2024-05-19 22:07 UTC
